export const CONTENT_SECURITY_POLICY = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self'",
  "img-src 'self' data: wovennote-attachment:",
  "media-src 'self' wovennote-attachment:",
  "font-src 'self'",
  "connect-src 'self'",
  "object-src 'none'",
  "base-uri 'none'",
  "form-action 'none'",
  'frame-src https://www.youtube-nocookie.com',
  "frame-ancestors 'none'",
  "worker-src 'none'",
  "script-src-attr 'none'",
  "style-src-attr 'none'",
].join('; ')
